language:
  - cpp

sudo: required

addons:
  apt:
    packages:
    - g++ make
    - ccache
    - libsdl2-dev
    - libsdl2-net-dev
    - libcurl4-openssl-dev
    - libjpeg-turbo8-dev
    - libmpeg2-4-dev
    - libogg-dev
    - libvorbis-dev
    - libflac-dev
    - libmad0-dev
    - libpng-dev
    - libtheora-dev
    - libfaad-dev
    - libfluidsynth-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libieee1284-3-dev
    - libsndio-dev
    - libunity-dev
  homebrew:
    packages:
    - ccache
    - sdl2
    - sdl2_net
    - curl
    - jpeg-turbo
    - libmpeg2
    - a52dec
    - libogg
    - libvorbis
    - flac
    - mad
    - libpng
    - theora
    - faad2
    - fluid-synth
    - freetype
    - zlib
    - pandoc
    - jack
    update: true

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: ccache
    - os: linux
      compiler: clang
      cache: ccache
      before_script:
        - sudo ln -s $(which ccache) /usr/lib/ccache/clang
        - sudo ln -s $(which ccache) /usr/lib/ccache/clang++
    - os: osx
      compiler: clang
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup

dist: xenial

script:
  - export PATH="/usr/local/opt/ccache/libexec:/usr/lib/ccache:$PATH"
  - ./configure --enable-all-engines --enable-opl2lpt
  - make -j 2
  - make test
  - make devtools

notifications:
  irc:
    channels:
      - "chat.freenode.net#scummvm"
    on_success: change
    on_failure: always
