name: CI
on: [push, pull_request]
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [win32, x64, arm64]
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: vcpkg
        uses: lukka/run-vcpkg@v2
        with:
          setupOnly: true
          vcpkgGitCommitId: d4a415b7fa3f0d0ea14a789d5778abfc666ef2d0
      - name: test env
        run: |
          echo ${env:VCPKG_ROOT}/vcpkg
      - name: ls vcpkg
        run: |
          ls ${env:VCPKG_ROOT}
      - name: vcpkg help
        run: |
          ${env:VCPKG_ROOT}/vcpkg.exe --help
      - name: Install vcpkg libs
        run: |
          ${env:VCPKG_ROOT}/vcpkg.exe install zlib:${env:PLATFORM}-windows
